import 'records/domain/entities/resource_spec.dart';

/// true  = sign in with the Elyvori API and show the live agents dashboard.
/// false = a standalone offline-first app that opens straight on its modules.
const bool useElyvoriAgents = false;

/// The modules of this app, generated by Elyvori from the client's request.
const List<ResourceSpec> appResources = <ResourceSpec>[
  ResourceSpec(
    key: 'bookings',
    title: 'الحجوزات',
    icon: 'bookings',
    description: 'إدارة حجوزات الجلسات والعملاء',
    fields: [
      FieldSpec(key: 'client_name', label: 'اسم العميل', type: FieldType.text, required: true),
      FieldSpec(key: 'phone', label: 'رقم الهاتف', type: FieldType.phone, required: true),
      FieldSpec(key: 'booking_date', label: 'تاريخ الحجز', type: FieldType.date, required: true),
      FieldSpec(key: 'number_of_people', label: 'عدد الأشخاص', type: FieldType.number, required: true),
      FieldSpec(key: 'confirmed', label: 'مؤكد', type: FieldType.boolean, required: false),
    ],
  ),
  ResourceSpec(
    key: 'products',
    title: 'المنتجات',
    icon: 'product',
    description: 'قائمة المنتجات والأسعار',
    fields: [
      FieldSpec(key: 'product_name', label: 'اسم المنتج', type: FieldType.text, required: true),
      FieldSpec(key: 'price', label: 'السعر', type: FieldType.number, required: true),
      FieldSpec(key: 'category', label: 'التصنيف', type: FieldType.text, required: false),
      FieldSpec(key: 'available', label: 'متوفر', type: FieldType.boolean, required: true),
    ],
  ),
  ResourceSpec(
    key: 'orders',
    title: 'الطلبات',
    icon: 'orders',
    description: 'متابعة طلبات العملاء اليومية',
    fields: [
      FieldSpec(key: 'order_title', label: 'رقم أو عنوان الطلب', type: FieldType.text, required: true),
      FieldSpec(key: 'customer_name', label: 'اسم الزبون', type: FieldType.text, required: true),
      FieldSpec(key: 'total_amount', label: 'المبلغ الإجمالي', type: FieldType.number, required: true),
      FieldSpec(key: 'order_date', label: 'تاريخ الطلب', type: FieldType.date, required: true),
      FieldSpec(key: 'completed', label: 'مكتمل', type: FieldType.boolean, required: false),
    ],
  ),
  ResourceSpec(
    key: 'customers',
    title: 'الزباين',
    icon: 'customers',
    description: 'دليل معلومات وسجلات العملاء',
    fields: [
      FieldSpec(key: 'customer_name', label: 'اسم الزبون', type: FieldType.text, required: true),
      FieldSpec(key: 'phone', label: 'رقم الجوال', type: FieldType.phone, required: true),
      FieldSpec(key: 'email', label: 'البريد الإلكتروني', type: FieldType.email, required: false),
      FieldSpec(key: 'notes', label: 'ملاحظات عن الزبون', type: FieldType.longText, required: false),
    ],
  ),
  ResourceSpec(
    key: 'notes',
    title: 'ملاحظات',
    icon: 'task',
    description: 'تدوين الملاحظات والأفكار اليومية',
    fields: [
      FieldSpec(key: 'note_title', label: 'عنوان الملاحظة', type: FieldType.text, required: true),
      FieldSpec(key: 'content', label: 'التفاصيل', type: FieldType.longText, required: true),
      FieldSpec(key: 'note_date', label: 'التاريخ', type: FieldType.date, required: true),
    ],
  ),
];
